### ISSUE TITLE
Requesting assistance with moving code around in the dfmodules repo

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/daq-cmake#29] opened 2021-02-08 01:56 UTC
The purpose of this Issue is to ask for some assistance in moving source code around a bit in the dfmodules repository.  For example, moving method definitions into *.cpp files.  And moving files that are not plugins into the /src directory. 

In the next few comments in this Issue, I will copy in a few emails that have already been exchanged in these topics.
Thanks in advance for the help,
Kurt

**Comment by bieryAtFnal** [comment] 2021-02-08 02:01
Here is a copy of the email that I sent.

----------------------------------------

Hi guys,
I’ve tried to make some simple improvements to the way that the source code files are organized in the dfmodules repository, and I’ve run into some problems getting them to build, so I’d like to ask for your help.

My sense is that these changes are reasonable, and possibly even desirable, so it seems like it will be worthwhile to get them to compile.

Here are the changes:

1. I moved HDF5KeyTranslator.hpp and HDF5FileUtils.hpp from /plugins to /src/dfmodules.
   * This worked fine, so no questions there.
1. I tried to move one of the method definitions in HDF5KeyTranslator from its header file into a /src/HDF5KeyTranslator.cpp file.  I modified the CMakeLists.txt to add HDF5KeyTranslator to the list of files to compile into the dfmodules library.  I hope that I did that correctly.
   * This fails to build because it cannot find the dfmodules/hdf5datastore/Nljs.hpp file
1. I tried to move one of the method definitions in HDF5DataStore from its header file into its *.cpp file (still in the /plugins subdir).
   * This fails because the unit tests that make use of HDF5DataStore can no longer find this method definition in the link library path.  I tried adding the HDF5DataStore plugin to the library path for the relevant unit tests, but it’s not allowed to do that.

I have committed these changes to the feature/BuildChangeIdeas branch in the dfmodules repository in case you would like to take a look at them.  Of course, I can describe these desired changes in more detail sometime, if you want.

Once these changes are supports, I expect that we will be making and additional request to have the ability to compile different subsets of the files in /src into different libraries.
Thanks,
Kurt

---------------

Sorry, I should have mentioned that I created the feature/BuildChangeIdeas branch from the feature/Issue21_DataWritingFriendliness branch in the dfmodules repo.
So, if you are looking to see the changes that are unique to the feature/BuildChangeIdeas branch, you should use the following command

*  `git diff origin/feature/Issue21_DataWritingFriendliness`

And, yes, I realize now that a better name for the new branch would have been feature/CodeOrganizationChangeIdeas...

**Comment by bieryAtFnal** [comment] 2021-02-08 02:07
Here is Alessandro's reply

-----------------

   * Here are the changes:
	• I moved HDF5KeyTranslator.hpp and HDF5FileUtils.hpp from /plugins to /src/dfmodules.
		• This worked fine, so no questions there.
	• I tried to move one of the method definitions in HDF5KeyTranslator from its header file into a /src/HDF5KeyTranslator.cpp file.  I modified the CMakeLists.txt to add HDF5KeyTranslator to the list of files to compile into the dfmodules library.  I hope that I did that correctly.

There seem to be a .cpp missing here:
https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DUNE-2DDAQ_dfmodules_blob_feature_BuildChangeIdeas_CMakeLists.txt-23L15&d=DwIGaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=lfJn8IlK95ZGuafYS9SD4g&m=sTH5gqr87qoDSUEiZ7c6WYhTs2xOMMKlF9n7BexBrWA&s=oLKRSzo7VIKIbHcogq5cSyyuPQ4ME1ZPug7MoKNBBYY&e= 

		• This fails to build because it cannot find the dfmodules/hdf5datastore/Nljs.hpp file

Right, and the reason is that daq-cmake exclusively works in the plugin context, at the moment. The main library is unaware of plugins and their components by construction (the library meant to hold the code common to all plugins in the package, therefore plugins depend on the library, but the opposite is “forbidden”) so compilation is expected to fail.

This is a limitation of daq-cmake moo integration which provides code generation only for plugins whereas schema fragments like HDF5DataStoreFileNameParams and HDF5DataStoreFileLayoutParams have a broader scope and   should be treated as part of the main library. It’s something we’re painfully aware of. We have started capturing thoughts about how to improve the integration with moo here

https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_DUNE-2DDAQ_daq-2Dcmake_issues_27&d=DwIGaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=lfJn8IlK95ZGuafYS9SD4g&m=sTH5gqr87qoDSUEiZ7c6WYhTs2xOMMKlF9n7BexBrWA&s=KXG5LXX4hCMzYG5kCe1tlRHse8ai8XVwHtr0LjYUB-g&e= 

   * plus work has started on a couple of branches.
	• I tried to move one of the method definitions in HDF5DataStore from its header file into its *.cpp file (still in the /plugins subdir).
		• This fails because the unit tests that make use of HDF5DataStore can no longer find this method definition in the link library path.  I tried adding the HDF5DataStore plugin to the library path for the relevant unit tests, but it’s not allowed to do that.

This I don’t quite understand. What is the affected unittest? I haven’t looked carefully, but I can’t find the one using the method in question  - HDF5DataStore’s constructor, is that right?

   * I have committed these changes to the feature/BuildChangeIdeas branch in the dfmodules repository in case you would like to take a look at them.  Of course, I can describe these desired changes in more detail sometime, if you want.

Yes, the last one in particular. 

   * Once these changes are supported, I expect that we will be making and additional request to have the ability to compile different subsets of the files in /src into different libraries.

Regarding the request to have multiple libraries per package, can you prepare a few use-cases to support the request?
In the repository model we have adopted so far, where packages have no sub-packages, the number of libraries is limited to one to keep the package structure “simple”.
In case of need to split the functions across multiple libraries, the guideline is to create a new package.
Now, none of this is cast in stone, but a change to the current approach should be well motivated and a few good use-cases will certainly help the discussion.

Cheers,
Alessandro

P.S.: Out of curiosity, what is the reason for the src/dfmodules subdirectory?

**Comment by bieryAtFnal** [comment] 2021-02-08 02:24
Some responses from me:

- I've added the missing .cpp to the CMakeLists.txt file
- I wonder if the reason that the compilation of src/HDF5KeyTranslator.cpp fails to find dfmodules/hdf5datastore/Nljs.hpp is simply because files in /src don't have the generated headers under /src added to their include path
- unit tests HDF5Read_test and HDF5Write_test both create instances of HDF5DataStore using its constructor.
- the use case for multiple repositories is the following:
   - we want to put source code files that contain utility methods for the HDF5 storing of data in the /src code directory.  We could certainly include those files in the standard dfmodules library, along with source code files that are used by many classes in the dfmodules repo.  However, if applications choose to configure a different DataStore than the HDF5DataStore (someday, down the road), it would be nice if the HDF5 utility routines didn't need to be loaded into the application when they will not be needed.  It is my sense that putting them in a separate library will allow them to only be loaded when needed (that is, only compiled into the HDF5DataStore plugin).
- regarding the reason for the /src/dfmodules directory...  I've seen the presence of a /src/<packageName> directory in several repos, e.g. trigemu and readout.  It is under this directory that generated files seem to be stored.  My choice to put "internal" header files in directory was just based on my guess as to where they should go.  If instead, you tell me that they should go in /src, I can certainly do that.  But then, how should they be included in source code files in /src and /unittest?  
   
Thanks again.

**Comment by bieryAtFnal** [comment] 2021-02-08 02:33
It might be easier to deal with one of these issues at a time.  I can certainly back out some of the changes on the dfmodules:feature/BuildChangeIdeas branch so that only one change is present, and we could go from there.

**Comment by alessandrothea** [comment] 2021-02-08 13:41
> * I wonder if the reason that the compilation of src/HDF5KeyTranslator.cpp fails to find dfmodules/hdf5datastore/Nljs.hpp is simply because files in /src don't have the generated headers under /src added to their include path

The reason is actually because the headers are generated in `plugins/dfmodules` and not in `src/`. The code in `src/` doesn't have access to `plugins/` by construction

> * unit tests HDF5Read_test and HDF5Write_test both create instances of HDF5DataStore using its constructor.

Ah, yes. Thanks.  What dependencies are required to reproduce the issue? `develop` branches of `appfwk` and `dfmessages`?

> * the use case for multiple repositories is the following:
>   
>   * we want to put source code files that contain utility methods for the HDF5 storing of data in the /src code directory.  We could certainly include those files in the standard dfmodules library, along with source code files that are used by many classes in the dfmodules repo.  However, if applications choose to configure a different DataStore than the HDF5DataStore (someday, down the road), it would be nice if the HDF5 utility routines didn't need to be loaded into the application when they will not be needed.  It is my sense that putting them in a separate library will allow them to only be loaded when needed (that is, only compiled into the HDF5DataStore plugin).

Well, as I mentioned in my reply, the proposed solution is to move the HDF5 code to a separate repository.
There are several examples already of this pattern: `readout` & `flxlibs`, `cmdlib` & `restcmd` + `filecmd` which have worked well so far. Would this approach be problematic for the HDF5DataStore code?



> * regarding the reason for the /src/dfmodules directory...  I've seen the presence of a /src/ directory in several repos, e.g. trigemu and readout.  It is under this directory that generated files seem to be stored.  My choice to put "internal" header files in directory was just based on my guess as to where they should go.  If instead, you tell me that they should go in /src, I can certainly do that.  But then, how should they be included in source code files in /src and /unittest?

They're headers. Of course, makes sense. Got it.

**Comment by bieryAtFnal** [comment] 2021-02-08 14:49
NB: I just pushed some fixes to the code on the feature/BuildChangeIdeas branch.  Sorry for not catching the errors that I found sooner.

With those changes, I can get the compilation of src/HDF5KeyTranslator.cpp to work if I make the following change in daq-cmake/cmake/DAQ.cmake:

```
--- a/cmake/DAQ.cmake
+++ b/cmake/DAQ.cmake
@@ -134,6 +134,9 @@ function(daq_add_library)
     add_library(${libname} SHARED ${libsrcs})
     target_link_libraries(${libname} PUBLIC ${LIBOPTS_LINK_LIBRARIES}) 
     target_include_directories(${libname} PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include> $<INSTALL_INTERFACE:${CMAKE_INS
+
+    target_include_directories(${libname} PRIVATE $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/src> )
+
     _daq_set_target_output_dirs( ${libname} ${LIB_PATH} )
   else()
     add_library(${libname} INTERFACE)
```

(I feel that I haven't been explaining myself well with regard to that issue.  It seems to me that I'm asking for a simple fix.  Maybe what you are saying is that you don't want to make the change that I made in DAQ.cmake, though?)

There is now a Wiki page that describes the packages needed for pre-v2.4.0 development.  It is [here](https://github.com/DUNE-DAQ/minidaqapp/wiki/Instructions-for-setting-up-a-v2.2.0--to--v2.4.0-development-environment).  My sense is all of the packages listed there (with the corresponding branches listed there) are needed to try to build the dfmodules::feature/BuildChangeIdeas branch.

Moving the HDF5DataStore to a separate repository is a very reasonable solution, and I don't know of any technical reason why that wouldn't work.

**Comment by alessandrothea** [comment] 2021-02-08 16:59
Actually, it's my fault. I was absolutely convinced that code generated headers were created in `plugins/` (rather than in `src/`). Also, I was equally convinced that we had already included `src/` in the library's include path.

OK, so it seems all good to me. I'll implement your suggestion and make a PR.

**Comment by bieryAtFnal** [comment] 2021-02-08 17:20
Sounds good.  And, if I may ask the favor, could someone look at **_all_** of the build directives to see whether the /src area needs to be added to the INCLUDE path?  Hopefully, all types of builds will now be covered, but the piece-meal way of adding them has been a little painful.

Also, I'm fairly sure that you are already thinking about this, but I wanted to mention that someday, we may want to make the generated headers public by installing them under /include rather than underneath /src...

**Comment by alessandrothea** [comment] 2021-02-08 20:55
> Sounds good. And, if I may ask the favor, could someone look at **_all_** of the build directives to see whether the /src area needs to be added to the INCLUDE path? Hopefully, all types of builds will now be covered, but the piece-meal way of adding them has been a little painful.

Hilariously, that's already the case. The library code was the only one unable to include from `src/`

> Also, I'm fairly sure that you are already thinking about this, but I wanted to mention that someday, we may want to make the generated headers public by installing them under /include rather than underneath /src...

More or less. I mentioned today what generated code will be moved to a `build/<package>/` subdirectory, possibly distinguishing private from public headers which will be eventually installed.

**Comment by alessandrothea** [comment] 2021-02-08 23:03
Regarding the linking issue 
> * I tried to move one of the method definitions in HDF5DataStore from its header file into its *.cpp file (still in the /plugins subdir).
>  * This fails because the unit tests that make use of HDF5DataStore can no longer find this method definition in the link library path. I tried adding the HDF5DataStore plugin to the library path for the relevant unit tests, but it’s not allowed to do that.

That's right. Plugins are created as cmake MODULES, which cannot be directly linked.
This implies that a `HDF5DataStore` cannot be new'd directly, but must be created using the appropriate make function, which in the case of `DataStore` I believe to be...

https://github.com/DUNE-DAQ/dfmodules/blob/develop/include/dfmodules/DataStore.hpp#L137

Does that make sense?

**Comment by bieryAtFnal** [comment] 2021-02-08 23:22
It does make sense, but it seems dangerous to rely on that method, because it requires the *runtime* environment to be set up for the appropriate make function to work, given my tests.  Is this right?  Do we want to require that the build *and* runtime environments need to be set up before unit tests can be run?  I suspect not.

I wonder if a solution might be to introduce a little bit of indirection...  Maybe we create an HDF5DataStore class in /src and create a very thin plugin wrapper for it in /plugins.  Then, the unit tests can use the non-MODULE class from /src, and other code can create an instance using the MODULE methodology...

If this makes sense, I'd appreciate hints on how to 'create a very thin plugin wrapper'...

**Comment by alessandrothea** [comment] 2021-02-09 19:03
Right, but how's that going to help? Even if the class core is moved to the library and the library linked to the unittest, the library would be loaded at runtime. And for that to happen, the same runtime environment has to be set, hasn't it?

**Comment by bieryAtFnal** [comment] 2021-02-09 19:27
I may be missing something, but I don't think so.
I just ran a test in which I only set up the build environment, and I was able to run the StorageKey test.  That test picks up the StorageKey method definitions from the StorageKey.cpp file in the /src directory via the standard dfmodules library...
(The StorageKey test is currently commented out, but I can enable it on a branch, if you want.)

**Comment by bieryAtFnal** [comment] 2021-02-10 02:12
After chatting with Eric a bit, I'm wondering if we (dfmodule developers) should just create a base class in /src (e.g. HDF5DataStoreBase) that has all of the functionality that we want in an HDF5 DataStore, but is not a plugin.  That could be used in unit tests.  Then, in plugins, we could have a bare-bones HDF5DataStore class that inherits from HDF5DataStoreBase and get all of the functionality via inheritance.

**Comment by alessandrothea** [comment] 2021-02-10 06:26
> I may be missing something, but I don't think so.
> 
> I just ran a test in which I only set up the build environment, and I was able to run the StorageKey unit test.  That test picks up the StorageKey method definitions from the StorageKey.cpp file in the /src directory via the standard dfmodules library...
> 
> (The StorageKey unit test is currently commented out, but I can enable it on a branch, if you want.) 


You've right, unit tests (and other binaries, in fact) have the path of their linked libraries built-in as `rpath`. I didn't realise `rpath` is used because it's not there for installed binaries (I must be stripped during copy).

**Comment by alessandrothea** [comment] 2021-02-10 06:45
> After chatting with Eric a bit, I'm wondering if we (dfmodule developers) should just create a base class in /src (e.g. HDF5DataStoreBase) that has all of the functionality that we want in an HDF5 DataStore, but is not a plugin.  That could be used in unit tests.  Then, in plugins, we could have a bare-bones HDF5DataStore class that inherits from HDF5DataStoreBase and get all of the functionality via inheritance. 

Well, that would work, as in the unittests would compile, but at the price of added complexity and duplicated interface in the code, and specific code and dependencies moved from plugin to main library. And this pattern would repeat for any plugin that needs unittesting. It doesn't feel the right way forward.

I would rather consider 2 alternatives:
- change the cmake plugin attribute from `MODULE` to `SHARED`, allowing linking - which opens the door to the use of plugins as library in other places
- modify dbt-build to load the runtime environment when running unittests, ensuring that all the correct paths are set for the make method to work as expected.

**Comment by eflumerf** [comment] 2021-02-10 12:43
I'll vote for plugin libraries to be `SHARED`, this also gives us the ability to sub-class plugins if needed.

**Comment by bieryAtFnal** [comment] 2021-02-10 12:44
I also vote for plugin libraries to be SHARED.

**Comment by alessandrothea** [comment] 2021-02-10 13:00
Are plugins meant to be subclassed? I think not.

**Comment by alessandrothea** [comment] 2021-02-10 13:01
Was there any argument in favor of the `SHARED` attribute?
From the unittest perspective I'd argue that tests (unittests or others) are **supposed** to be run in the runtime environment and that not doing it is an anomaly that must be corrected.

**Comment by bieryAtFnal** [comment] 2021-02-10 13:08
I don't think that I have an argument for SHARED.  It just seemed easier (for you).
Now that you say that the unit tests should run in a runtime environment, I can see the good sense in doing that (the test environment would be better matched to running things for real and therefore can be better tests of what users will see).

**Comment by alessandrothea** [comment] 2021-02-10 13:34
Alright, working example coming up. You'll need:

- `daq-buildtools`: `thea/runtime_env_for_unittests`
- `dfmodules`: `origin/thea/runtime-env-unittest-example`

On top of the list of packages you pointed me to, @bieryAtFnal.
It seems to do the right thing for me, but please check.

P.S.: Unfortunately one is left to deal with the unique pointers inflexibility when it comes to casting, but that's life...

```c++
  std::unique_ptr<HDF5DataStore> data_store_ptr(static_cast<HDF5DataStore *>(make_data_store(conf).release()));
```

**Comment by alessandrothea** [comment] 2021-02-22 16:29
@bieryAtFnal Is there anything further to discuss for this issue?

**Comment by alessandrothea** [comment] 2021-02-22 16:29
(or can we close it?)

**Comment by bieryAtFnal** [comment] 2021-02-22 16:31
It can be closed.
Thanks

**Closed** 2021-02-22 16:34 UTC
